spring.application.name=Bank
spring.datasource.url=jdbc:postgresql://localhost:5432/shoppingdb

spring.datasource.username=postgres
spring.session.jdbc.initialize-schema=always
spring.datasource.password=wangpin0622
server.port=8081